version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
  
  pre_build:
    commands:
      - printenv
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - |
        BRANCH_NAME='main'
        if [ ! -z "$CODEBUILD_SOURCE_VERSION" ]; then
         BRANCH_NAME="$CODEBUILD_SOURCE_VERSION"
        fi

        IMAGE_TAG=develop-$BRANCH_NAME-$CODEBUILD_RESOLVED_SOURCE_VERSION;
        SERVICE_NAME=actix-web-demo
      - docker build -t $SERVICE_NAME:$IMAGE_TAG .
      - docker tag $SERVICE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo 'BYE'
      - docker images
      - docker push $REPOSITORY_URI:$IMAGE_TAG
