version: 0.2
env:
  secrets-manager:
      DOCKER_USERNAME: "shared/docker/credentials:username"
      DOCKER_PASSWORD: "shared/docker/credentials:password"

phases:
  install:
    runtime-versions:
      python: 3.13
  
  pre_build:
    commands:
      - printenv
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - |
        IMAGE_TAG=develop-$CODEBUILD_RESOLVED_SOURCE_VERSION;
        SERVICE_NAME=actix-web-demo
      - docker build -t $SERVICE_NAME:$IMAGE_TAG .
      - docker tag $SERVICE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo 'BYE'
      - docker images
      - docker push $REPOSITORY_URI:$IMAGE_TAG
