version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
  
  pre_build:
    commands:
      - printenv

  build:
    commands:
      - |
        IMAGE_TAG=develop-$CODEBUILD_RESOLVED_SOURCE_VERSION;
        SERVICE_NAME=actix-web-demo
      - docker build -t $SERVICE_NAME:$IMAGE_TAG .
      - docker tag $SERVICE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo 'BYE'
      - docker images
      - docker push $REPOSITORY_URI:$IMAGE_TAG
